name: Deploy Backend

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build de backend
        run: |
          npm install --omit-dev
          npm run build

      - name: Deploy y reiniciar backend con PM2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo mkdir -p /var/www/api
            sudo chown -R $USER:$USER /var/www/api

            # Limpiar contenido viejo y copiar el nuevo
            rm -rf /var/www/api/*
            cp -r ~/github/workspace/dist/* /var/www/api/

            command -v pm2 >/dev/null 2>&1 || sudo npm install -g pm2

            cd /var/www/api
            pm2 restart api || pm2 start index.js --name api
            pm2 save

